bind 127.0.0.1 ::1
protected-mode yes
port 6381
daemonize no
supervised systemd
dir /var/lib/helixmind-redis
dbfilename dump.rdb
appendonly yes
appendfilename "appendonly.aof"
save 900 1
save 300 10
loglevel notice
logfile /var/log/helixmind/redis.log
pidfile /run/helixmind-redis/redis-server.pid
