'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ProtectedPage } from '../../../components/ProtectedPage';

type Publication = { publicationId: string; title: string; identifiers: { pmid: string | null; pmcid: string | null; doi: string | null }; source: string; counts: Record<string, number>; relevance: { score: number; formulaVersion: string; meaning: string }; contributions: { evidence: { id: string; text: string; polarity: string | null }[]; claims: { id: string; text: string }[]; relationships: { id: string; predicate: string; stance: string }[]; propositions: { id: string; text: string }[]; hypotheses: { id: string; statement: string; status: string }[] } };
type Intelligence = { publications: Publication[]; landscape: Record<string, number>; coverage: { note: string; propositionPublicationSupport: { propositionId: string; publicationCount: number; coverage: string }[] } };
type Snapshot = { id: string; snapshotNumber: number };
type Diff = { publicationsAdded: unknown[]; publicationsRemoved: unknown[]; publicationsRetained: unknown[]; contributionChanges: { publicationId: string; title: string; changes: Record<string, { added: string[]; removed: string[] }> }[] };
type Run = { id: string; runNumber: number; status: string; snapshotId: string | null };
type SemanticExtraction = { extractionId: string; publicationId: string; evidenceId: string; claimId: string | null; subject: string | null; subjectType: string | null; predicate: string | null; object: string | null; objectType: string | null; sourceSpan: string | null; sourceLocator: { start?: number; end?: number; source_location?: string } | null; semanticType: string | null; provider: string; model: string; extractionVersion: string; validationStatus: string; validationErrors: string[]; graphRelationshipId: string | null; extractionRunId: string; contentHash: string };

export default function InvestigationLiteraturePage() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<Intelligence | null>(null);
  const [error, setError] = useState('');
  const [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const [leftSnapshot, setLeftSnapshot] = useState('');
  const [rightSnapshot, setRightSnapshot] = useState('');
  const [diff, setDiff] = useState<Diff | null>(null);
  const [diffError, setDiffError] = useState('');
  const [runs, setRuns] = useState<Run[]>([]);
  const [extractions, setExtractions] = useState<SemanticExtraction[]>([]);
  const [selectedRun, setSelectedRun] = useState('');
  const [extractionBusy, setExtractionBusy] = useState(false);
  const [extractionMessage, setExtractionMessage] = useState('');
  useEffect(() => { fetch(`/api/backend/api/v1/investigations/${id}/literature/intelligence`, { cache: 'no-store' }).then(async response => { if (!response.ok) throw new Error(response.status === 404 ? 'Investigation not found.' : 'Literature intelligence could not be loaded.'); setData(await response.json()); }).catch(value => setError(value.message)); fetch(`/api/backend/api/v1/investigations/${id}/snapshots`, { cache: 'no-store' }).then(response => response.ok ? response.json() : []).then((rows: Snapshot[]) => { setSnapshots(rows); setLeftSnapshot(rows[1]?.id ?? ''); setRightSnapshot(rows[0]?.id ?? ''); }).catch(() => setSnapshots([])); fetch(`/api/backend/api/v1/investigations/${id}/runs`, { cache: 'no-store' }).then(response => response.ok ? response.json() : []).then((rows: Run[]) => { const completed = rows.filter(row => row.status === 'COMPLETED' && row.snapshotId); setRuns(completed); setSelectedRun(completed[0]?.id ?? ''); }).catch(() => setRuns([])); fetch(`/api/backend/api/v1/investigations/${id}/literature/semantic-extractions`, { cache: 'no-store' }).then(response => response.ok ? response.json() : { extractions: [] }).then(value => setExtractions(value.extractions ?? [])).catch(() => setExtractions([])); }, [id]);
  async function compare() { setDiffError(''); setDiff(null); const query = new URLSearchParams({ leftSnapshotId: leftSnapshot, rightSnapshotId: rightSnapshot }); const response = await fetch(`/api/backend/api/v1/investigations/${id}/literature/compare?${query}`, { cache: 'no-store' }); if (!response.ok) { setDiffError('Literature snapshots could not be compared.'); return; } setDiff(await response.json()); }
  async function extractSemantics() { setExtractionBusy(true); setExtractionMessage('Semantic extraction is using stored abstract evidence only.'); try { const response = await fetch(`/api/backend/api/v1/investigations/${id}/literature/semantic-extractions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_run_id: selectedRun }) }); const value = await response.json(); if (!response.ok) throw new Error(value.detail || 'Semantic extraction failed.'); setExtractionMessage(`${value.validCount} validated · ${value.rejectedCount} rejected · ${value.projectedCount} graph relations projected · ${value.provider} / ${value.model}`); const result = await fetch(`/api/backend/api/v1/investigations/${id}/literature/semantic-extractions`, { cache: 'no-store' }); if (result.ok) setExtractions((await result.json()).extractions ?? []); } catch (value) { setExtractionMessage(value instanceof Error ? value.message : 'Semantic extraction failed.'); } finally { setExtractionBusy(false); } }
  return <ProtectedPage eyebrow="INVESTIGATION / LITERATURE INTELLIGENCE" title="Literature landscape."><div className="literature-page">
    <Link className="button button-ghost button-small" href={`/investigations/${id}`}>← Investigation</Link>
    {error ? <div className="panel"><p className="error-text">{error}</p></div> : !data ? <div className="panel"><p>Loading investigation literature…</p></div> : <>
      <div className="health-grid">{[['Publications', data.landscape.totalPublications], ['Evidence bearing', data.landscape.evidenceBearingPublications], ['Graph linked', data.landscape.graphContributingPublications], ['Proposition linked', data.landscape.propositionContributingPublications], ['Hypothesis linked', data.landscape.hypothesisContributingPublications]].map(([name, value]) => <div className="health-card" key={String(name)}><span>{name}</span><b>{value}</b></div>)}</div>
      {snapshots.length > 1 && <section className="panel"><p className="eyebrow">RUN-TO-RUN LITERATURE</p><h2>Compare immutable snapshots</h2><div className="filter-row"><label>Earlier snapshot<select value={leftSnapshot} onChange={event => setLeftSnapshot(event.target.value)}>{snapshots.map(row => <option value={row.id} key={row.id}>Snapshot {row.snapshotNumber}</option>)}</select></label><label>Later snapshot<select value={rightSnapshot} onChange={event => setRightSnapshot(event.target.value)}>{snapshots.map(row => <option value={row.id} key={row.id}>Snapshot {row.snapshotNumber}</option>)}</select></label><button className="button button-small" disabled={!leftSnapshot || !rightSnapshot || leftSnapshot === rightSnapshot} onClick={() => void compare()}>Compare</button></div>{diffError && <p className="error-text">{diffError}</p>}{diff && <><p>{diff.publicationsAdded.length} new · {diff.publicationsRemoved.length} no longer retrieved · {diff.publicationsRetained.length} retained publications</p>{diff.contributionChanges.map(change => <p className="paper-meta" key={change.publicationId}>{change.title}: {Object.entries(change.changes).map(([kind, values]) => `${kind} +${values.added.length}/−${values.removed.length}`).join(' · ')}</p>)}<small>Comparison reads immutable snapshot manifests; historical runs are unchanged.</small></>}</section>}
      <p className="phase-disclaimer">Relevance is deterministic investigation linkage (formula {data.publications[0]?.relevance.formulaVersion ?? 'literature-relevance-v1'}), not evidence confidence or scientific truth. {data.coverage.note}</p>
      <section className="panel semantic-extraction-panel"><p className="eyebrow">M5 / SOURCE EVIDENCE</p><h2>Semantic extraction pilot</h2><p className="muted-copy">Candidate relations interpret persisted source evidence. A validated extraction is still an interpretation, not scientific fact or evidence confidence.</p><div className="filter-row"><label>Completed source run<select value={selectedRun} onChange={event => setSelectedRun(event.target.value)}><option value="">Choose run</option>{runs.map(run => <option key={run.id} value={run.id}>Run {run.runNumber}</option>)}</select></label><button className="button button-small" disabled={!selectedRun || extractionBusy} onClick={() => void extractSemantics()}>{extractionBusy ? 'Extracting…' : 'Extract stored evidence'}</button></div>{extractionMessage && <p className="paper-meta" role="status">{extractionMessage}</p>}{extractions.length ? <div className="semantic-extraction-list">{extractions.map(item => <details className="query-callout" key={item.extractionId}><summary>{item.subject || 'Unresolved candidate'} · {item.predicate || 'relation unavailable'} · {item.object || 'unresolved'} — {item.validationStatus}</summary><p><b>Source evidence:</b> {item.sourceSpan || 'No valid source span recorded.'}</p><small>Publication {item.publicationId} · Evidence {item.evidenceId}{item.claimId ? ` · Claim ${item.claimId}` : ''}{item.sourceLocator ? ` · ${item.sourceLocator.source_location || 'abstract'} ${item.sourceLocator.start}–${item.sourceLocator.end}` : ''}</small><p className="paper-meta">{item.semanticType || 'type unavailable'} · {item.provider} / {item.model} · {item.extractionVersion} · extraction run {item.extractionRunId}</p><p className="paper-meta">Validation: {item.validationStatus}{item.validationErrors.length ? ` · ${item.validationErrors.join(', ')}` : ''} · {item.graphRelationshipId ? 'Projected into the investigation graph' : 'Not projected into the graph'}</p><small>Candidate hash {item.contentHash}</small><Link href={`/investigations/${id}/literature/${item.publicationId}`}>Open source publication ↗</Link></details>)}</div> : <p className="muted-copy">No semantic extraction candidates have been recorded for this investigation.</p>}</section>
      {data.publications.map(paper => <article className="paper-card" key={paper.publicationId}>
        <div className="paper-card-top"><span className="source-label">{paper.source}</span><span className="relevance-label">Relevance {Math.round(paper.relevance.score * 100)}%</span></div>
        <h3><Link href={`/investigations/${id}/literature/${paper.publicationId}`}>{paper.title}</Link></h3>
        <p className="paper-meta">{paper.counts.evidence} evidence · {paper.counts.claims} claims · {paper.counts.entities} entities · {paper.counts.relationships} relationships · {paper.counts.propositions} propositions · {paper.counts.hypotheses} hypotheses</p>
        <div className="paper-card-bottom">{paper.identifiers.pmid && <span>PMID {paper.identifiers.pmid}</span>}{paper.identifiers.doi && <span>DOI {paper.identifiers.doi}</span>}{paper.identifiers.pmcid && <span>PMCID {paper.identifiers.pmcid}</span>}</div>
        {paper.contributions.evidence.map(item => <div className="evidence-card" key={item.id}><p>{item.text}</p><small>{item.polarity || 'Polarity unavailable'} · source evidence</small></div>)}
        {paper.contributions.relationships.map(item => <p className="paper-meta" key={item.id}>Graph relationship: {item.predicate} · {item.stance}</p>)}
        {paper.contributions.propositions.map(item => <p className="paper-meta" key={item.id}>Proposition: {item.text}</p>)}
        {paper.contributions.hypotheses.map(item => <p className="paper-meta" key={item.id}>Hypothesis: {item.statement} · {item.status}</p>)}
      </article>)}
      {data.publications.length === 0 && <div className="panel empty-state"><h3>No retrieved publications</h3><p>Run literature retrieval for this investigation to build an evidence linked landscape.</p></div>}
      <div className="panel"><p className="eyebrow">LIMITED SUPPORT</p><h2>Proposition coverage</h2>{data.coverage.propositionPublicationSupport.length ? data.coverage.propositionPublicationSupport.map(item => <p className="paper-meta" key={item.propositionId}>{item.coverage} · {item.publicationCount} publications · proposition {item.propositionId.slice(0, 8)}</p>) : <p className="muted-copy">No persisted proposition publication links are available yet.</p>}</div>
    </>}
  </div></ProtectedPage>;
}
