'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ProtectedPage } from '../../../../components/ProtectedPage';

type Contribution = { publicationId: string; title: string; source: string; identifiers: { pmid: string | null; pmcid: string | null; doi: string | null }; metadata: { authors: string[] | null; journal: string | null; publicationDate: string | null }; retrieval: { query: string | null; source: string | null; discoveredAt: string | null }; relevance: { score: number; formulaVersion: string; inputs: Record<string, number>; weights: Record<string, number>; meaning: string }; counts: Record<string, number>; contributions: { evidence: { id: string; text: string; sourceLocation: string; sourceSpan: Record<string, number> | null; polarity: string | null }[]; claims: { id: string; text: string }[]; entities: { id: string; name: string; type: string }[]; relationships: { id: string; subjectEntityId: string; predicate: string; objectEntityId: string; stance: string }[]; propositions: { id: string; text: string }[]; hypotheses: { id: string; statement: string; status: string }[] } };

export default function InvestigationPublicationPage() {
  const { id, paperId } = useParams<{ id: string; paperId: string }>();
  const [item, setItem] = useState<Contribution | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { fetch(`/api/backend/api/v1/investigations/${id}/literature/publications/${paperId}`, { cache: 'no-store' }).then(async response => { if (!response.ok) throw new Error(response.status === 404 ? 'Publication not found in this investigation.' : 'Publication contribution could not be loaded.'); setItem(await response.json()); }).catch(value => setError(value.message)); }, [id, paperId]);
  return <ProtectedPage eyebrow="INVESTIGATION / LITERATURE / PUBLICATION" title={item?.title ?? 'Publication contribution.'}><div className="paper-detail">
    <Link className="button button-ghost button-small" href={`/investigations/${id}/literature`}>← Literature landscape</Link>
    {error ? <div className="panel"><p className="error-text">{error}</p></div> : !item ? <div className="panel"><p>Loading publication contribution…</p></div> : <>
      <section className="panel"><p className="eyebrow">PUBLICATION → INVESTIGATION</p><div className="paper-card-top"><span className="source-label">{item.source}</span><span className="relevance-label">Relevance {Math.round(item.relevance.score * 100)}%</span></div><p className="paper-meta">{item.metadata.authors?.join(', ') || 'Author information unavailable'} · {item.metadata.journal || 'Journal unavailable'} · {item.metadata.publicationDate || 'Publication date unavailable'}</p><div className="paper-identifiers">{item.identifiers.pmid && <span>PMID <b>{item.identifiers.pmid}</b></span>}{item.identifiers.pmcid && <span>PMCID <b>{item.identifiers.pmcid}</b></span>}{item.identifiers.doi && <span>DOI <b>{item.identifiers.doi}</b></span>}</div><p className="phase-disclaimer">{item.relevance.meaning} Formula {item.relevance.formulaVersion}. Inputs and weights are inspectable below.</p><div className="metric-grid">{Object.entries(item.counts).map(([key, value]) => <div className="metric-card" key={key}><span>{key}</span><b>{value}</b></div>)}</div><details><summary>Relevance inputs and weights</summary><pre>{JSON.stringify({ inputs: item.relevance.inputs, weights: item.relevance.weights }, null, 2)}</pre></details></section>
      <section className="panel"><p className="eyebrow">RETRIEVAL PROVENANCE</p><h2>Source search</h2><p>{item.retrieval.source || item.source} · {item.retrieval.discoveredAt || 'retrieval timestamp unavailable'}</p><code>{item.retrieval.query || 'Search query unavailable'}</code></section>
      <section className="panel"><p className="eyebrow">SOURCE EVIDENCE</p><h2>Evidence contribution</h2>{item.contributions.evidence.length ? item.contributions.evidence.map(evidence => <article className="evidence-card" key={evidence.id}><p>{evidence.text}</p><small>{evidence.polarity || 'Polarity unavailable'} · {evidence.sourceLocation}{evidence.sourceSpan ? ` · ${evidence.sourceSpan.start}–${evidence.sourceSpan.end}` : ''}</small></article>) : <p className="muted-copy">This publication has no persisted evidence contribution in this investigation.</p>}{item.contributions.claims.map(claim => <div className="query-callout" key={claim.id}><span>Claim</span><p>{claim.text}</p></div>)}</section>
      <section className="panel"><p className="eyebrow">KNOWLEDGE GRAPH</p><h2>Connected records</h2>{item.contributions.entities.map(entity => <div className="query-callout" key={entity.id}><span>{entity.type}</span><p>{entity.name}</p><Link href={`/knowledge?investigationId=${id}&entityId=${entity.id}`}>Open entity in Knowledge Graph ↗</Link></div>)}{item.contributions.relationships.map(relation => <div className="query-callout" key={relation.id}><span>{relation.stance}</span><p>{relation.subjectEntityId} · {relation.predicate} · {relation.objectEntityId}</p><Link href={`/investigations/${id}/literature/graph/relationship/${relation.id}`}>Inspect supporting publications ↗</Link></div>)}{item.contributions.propositions.map(proposition => <div className="query-callout" key={proposition.id}><span>Proposition</span><p>{proposition.text}</p><Link href={`/investigations/${id}/literature/graph/proposition/${proposition.id}`}>Inspect supporting publications ↗</Link></div>)}{item.contributions.hypotheses.map(hypothesis => <div className="query-callout" key={hypothesis.id}><span>Hypothesis · {hypothesis.status}</span><p>{hypothesis.statement}</p><Link href={`/investigations/${id}/literature/graph/hypothesis/${hypothesis.id}`}>Inspect supporting publications ↗</Link></div>)}</section>
    </>}
  </div></ProtectedPage>;
}
