'use client';

import { useState } from 'react';
import { BeakerIcon, BookOpenIcon, ChartBarIcon, ChevronRightIcon, CircleStackIcon, CommandLineIcon, DocumentMagnifyingGlassIcon, HomeIcon, LightBulbIcon, MagnifyingGlassIcon, PlusIcon, ShieldCheckIcon, SparklesIcon, Squares2X2Icon } from '@heroicons/react/24/outline';

const activities = [
  ['check', 'Research question formulated', 'just now'], ['check', 'Literature retrieved', '2m ago'], ['check', 'Evidence extracted', '4m ago'], ['check', 'Knowledge graph updated', '5m ago'], ['warn', 'Contradiction detected', '6m ago'], ['check', 'Hypothesis updated', '7m ago'],
];
const evidence = [
  { tag: 'SUPPORTS', color: 'green', title: 'CRISPR gene editing for sickle cell disease', text: 'Exagamglogene autotemcel demonstrated durable increases in fetal hemoglobin and reduced vaso-occlusive crises in a phase 1/2 study.', source: 'Frangoul et al. · NEJM · 2021', score: '0.92' },
  { tag: 'SUPPORTS', color: 'green', title: 'Clinical efficacy of base editing', text: 'Early clinical data supports a single-dose approach, though long-term safety and durability remain under observation.', source: 'Muench et al. · Nature Medicine · 2024', score: '0.81' },
  { tag: 'CONTRADICTS', color: 'red', title: 'Off-target edits remain a concern', text: 'Unintended edits and conditioning toxicity require longer follow-up before broad clinical deployment.', source: 'Gonzalez et al. · Cell · 2023', score: '0.67' },
];

function Brand() { return <div className="brand"><img src="/helixmindcoverimage.jpg" alt="" /><div><strong>Helix<span>Mind</span></strong><small>SCIENTIFIC INTELLIGENCE</small></div></div>; }
function Icon({ children }: { children: React.ReactNode }) { return <span className="nav-icon">{children}</span>; }

export default function Home() {
  const [active, setActive] = useState('Dashboard'); const [showNew, setShowNew] = useState(false); const [question, setQuestion] = useState(''); const [submitted, setSubmitted] = useState(false);
  const nav = [['Workspace', [['Dashboard', <HomeIcon />, ''], ['Explore', <BookOpenIcon />, '']]], ['Research', [['Investigate', <DocumentMagnifyingGlassIcon />, 'live'], ['Hypotheses', <LightBulbIcon />, ''], ['Papers', <DocumentMagnifyingGlassIcon />, ''], ['Knowledge graph', <CircleStackIcon />, '']]], ['System', [['OmegaClaw', <SparklesIcon />, ''], ['MeTTa console', <CommandLineIcon />, ''], ['Settings', <Squares2X2Icon />, '']]]];
  return <main className="app-shell"><aside className="sidebar"><Brand /><div className="workspace-pill"><span className="workspace-dot" /> CRISPR / Core <ChevronRightIcon /></div><nav>{nav.map(([section, links]) => <div className="nav-group" key={section as string}><label>{section as string}</label>{(links as any[]).map(([name, icon, badge]) => <button className={active === name ? 'nav-link active' : 'nav-link'} key={name} onClick={() => setActive(name)}><Icon>{icon}</Icon>{name}{badge === 'live' && <em>●</em>}</button>)}</div>)}</nav><div className="sidebar-bottom"><div className="system-status"><span className="pulse" /><div><b>Systems operational</b><small>OmegaClaw · MeTTa online</small></div></div><div className="user"><span>AK</span><div><b>Alex Kim</b><small>Researcher</small></div><ChevronRightIcon /></div></div></aside>
    <section className="content"><header className="topbar"><div className="crumb"><span>Workspace</span><ChevronRightIcon /><b>{active}</b></div><div className="top-actions"><button className="icon-button"><MagnifyingGlassIcon /></button><button className="shortcut">⌘ K</button><button className="new-button" onClick={() => setShowNew(true)}><PlusIcon /> New investigation</button></div></header>
      <div className="page"><div className="eyebrow"><span className="eyebrow-mark"><SparklesIcon /></span> HELIXMIND / {active.toUpperCase()}</div><div className="page-heading"><div><h1>Good morning, Alex.</h1><p>Here’s the state of your scientific workspace.</p></div><span className="date">THURSDAY, AUGUST 20, 2026</span></div>
        <div className="metrics"><Metric label="Active investigations" value="03" detail="1 running now" accent="gold"/><Metric label="Evidence collected" value="1,284" detail="↑ 18.4% this month" accent="green"/><Metric label="Avg. confidence" value="78.6%" detail="Across 12 hypotheses" accent="red"/><Metric label="Knowledge gaps" value="17" detail="4 high priority" accent="purple"/></div>
        <div className="dashboard-grid"><div className="primary-column"><div className="section-title"><div><h2>Active investigations</h2><p>Research threads currently in progress</p></div><button className="text-button">View all <ChevronRightIcon /></button></div><div className="investigation-card featured"><div className="card-top"><span className="status-live"><i /> LIVE INVESTIGATION</span><span>INV-2048</span></div><h3>Is CRISPR-based intervention a scientifically supported therapeutic strategy for sickle-cell disease?</h3><div className="progress-row"><div className="progress"><span style={{width:'72%'}} /></div><b>72%</b><span>Researching</span></div><div className="card-footer"><span><SparklesIcon /> OmegaClaw is reasoning</span><span>Updated 2 min ago <ChevronRightIcon /></span></div></div><div className="investigation-card"><div className="card-top"><span className="status-review"><i /> AWAITING REVIEW</span><span>INV-2045</span></div><h3>Evaluating prime editing for inherited retinal disorders</h3><div className="mini-stats"><span><b>68</b> papers</span><span><b>342</b> entities</span><span><b>84%</b> confidence</span></div><div className="card-footer"><span>Last activity 3 hours ago</span><span className="muted">Open thread <ChevronRightIcon /></span></div></div><div className="section-title recent-title"><div><h2>Recent investigations</h2><p>Your latest scientific questions</p></div><button className="text-button">See archive <ChevronRightIcon /></button></div><div className="recent-list"><Recent title="Can base editing reduce off-target effects?" meta="Completed · Aug 18, 2026" score="91%"/><Recent title="What are the current limits of in-vivo delivery?" meta="Completed · Aug 14, 2026" score="74%"/></div></div>
          <aside className="right-column"><div className="section-title"><div><h2>Agent activity</h2><p>OmegaClaw research orchestration</p></div><span className="live-dot">LIVE</span></div><div className="activity-card">{activities.map(([type, text, time]) => <div className="activity" key={text}><span className={type === 'warn' ? 'activity-icon warn' : 'activity-icon'}>{type === 'warn' ? '!' : '✓'}</span><div><b>{text}</b><small>{time}</small></div></div>)}<button className="activity-more">View full activity <ChevronRightIcon /></button></div><div className="insight-card"><div className="insight-head"><span><LightBulbIcon /></span><b>RESEARCH INSIGHT</b></div><h3>Confidence shifted on your active hypothesis</h3><p>New clinical evidence increased support for therapeutic efficacy, while long-term safety remains unresolved.</p><div className="insight-chart"><span /><span /><span /><span /><span /><span /><span /><span /><span /></div><div className="insight-foot"><b>+0.07</b><span>over the last 7 days</span></div></div><div className="tech-card"><div className="tech-row"><span className="tech-logo">Ω</span><div><b>OmegaClaw</b><small>Research orchestration</small></div><span className="online">ONLINE</span></div><div className="tech-row"><span className="metta-logo">∴</span><div><b>MeTTa</b><small>Knowledge reasoning</small></div><span className="online">ONLINE</span></div><button onClick={() => setActive('MeTTa console')}>Open transparency console <ChevronRightIcon /></button></div></aside></div>
      </div></section>{showNew && <div className="modal-backdrop" onClick={() => setShowNew(false)}><div className="modal" onClick={e => e.stopPropagation()}><div className="modal-icon"><BeakerIcon /></div><span className="eyebrow">NEW INVESTIGATION</span><h2>What would you like to investigate?</h2><p>OmegaClaw will plan the research, gather evidence, and map the reasoning for you.</p><textarea autoFocus placeholder="e.g. Is CRISPR-based intervention a scientifically supported therapeutic strategy for sickle-cell disease?" value={question} onChange={e => setQuestion(e.target.value)} /><div className="modal-actions"><button className="cancel" onClick={() => setShowNew(false)}>Cancel</button><button className="new-button" disabled={!question.trim()} onClick={() => {setSubmitted(true); setShowNew(false)}}><SparklesIcon /> Start investigation</button></div></div></div>}{submitted && <div className="toast"><span>✓</span><div><b>Investigation queued</b><small>OmegaClaw is formulating a research plan.</small></div><button onClick={() => setSubmitted(false)}>×</button></div>}</main>;
}

function Metric({label,value,detail,accent}:{label:string,value:string,detail:string,accent:string}) { return <div className="metric"><span className={'metric-icon '+accent}>{accent === 'gold' ? '◌' : accent === 'green' ? '✦' : accent === 'red' ? '◈' : '⌁'}</span><div><small>{label}</small><strong>{value}</strong><em className={accent === 'red' || accent === 'purple' ? '' : 'positive'}>{detail}</em></div></div> }
function Recent({title,meta,score}:{title:string,meta:string,score:string}) { return <div className="recent-item"><div className="recent-symbol"><ChartBarIcon /></div><div><b>{title}</b><small>{meta}</small></div><strong>{score}<small>confidence</small></strong><ChevronRightIcon /></div> }
