import Link from 'next/link';

import { Brand } from './components/Brand';

const capabilities = [
  ['01', 'Scientific investigations', 'Move from a precise question to a traceable research record.'],
  ['02', 'Evidence mapping', 'Keep source evidence distinct from interpretation and inference.'],
  ['03', 'Knowledge relationships', 'Represent genes, diseases, studies and findings as structured knowledge.'],
  ['04', 'Contradiction detection', 'Surface competing findings without overstating what the literature proves.'],
  ['05', 'Confidence tracking', 'Make uncertainty visible across the evidence chain.'],
  ['06', 'Knowledge gaps', 'Identify unanswered questions and relationships that remain unverified.'],
];

const workflow = ['Question', 'Plan', 'Literature', 'Evidence', 'Knowledge', 'Reasoning', 'Hypotheses', 'Gaps'];

export default function Home() {
  return <main className="landing"><header className="landing-nav"><Brand /><nav><a href="#method">Method</a><a href="#stack">Reasoning stack</a><a href="#crispr">CRISPR</a></nav><div className="nav-actions"><Link href="/login" className="text-link">Sign in</Link><Link href="/login" className="button button-small">Start researching</Link></div></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">EVIDENCE-LED RESEARCH INTELLIGENCE</p><h1>Reason over<br /><em>scientific evidence.</em></h1><p className="hero-lede">HelixMind helps researchers navigate literature, structure knowledge, and examine uncertainty across complex biotechnology questions.</p><div className="hero-actions"><Link href="/login" className="button">Start researching <span>↗</span></Link><Link href="/demo" className="button button-ghost">Try demo <span>→</span></Link></div><p className="hero-note">Built for biotechnology, genomics and CRISPR research. Conceptual visualizations are clearly labelled and never presented as evidence.</p></div><div className="network" aria-label="Conceptual scientific knowledge network"><div className="network-grid" /><svg viewBox="0 0 540 500" role="img"><g className="network-lines"><line x1="90" y1="105" x2="255" y2="205" /><line x1="255" y1="205" x2="445" y2="116" /><line x1="255" y1="205" x2="174" y2="375" /><line x1="255" y1="205" x2="400" y2="366" /><line x1="445" y1="116" x2="400" y2="366" /><line x1="174" y1="375" x2="400" y2="366" /></g><g className="network-nodes"><circle cx="90" cy="105" r="28" /><circle cx="255" cy="205" r="43" /><circle cx="445" cy="116" r="32" /><circle cx="174" cy="375" r="30" /><circle cx="400" cy="366" r="35" /></g></svg><span className="node-label node-a">GENE <b>HBB</b></span><span className="node-label node-b">DISEASE <b>SICKLE CELL</b></span><span className="node-label node-c">STUDY <b>CLINICAL</b></span><span className="node-label node-d">THERAPY</span><span className="network-caption">CONCEPTUAL VISUALIZATION / NOT SCIENTIFIC EVIDENCE</span></div></section>
    <section className="signal-row"><span>AN INTELLIGENCE LAYER FOR SCIENTIFIC WORK</span><span>Literature is expanding faster than manual synthesis.</span><span>Evidence deserves a reasoning trail.</span></section>
    <section id="method" className="section split-section"><div><p className="eyebrow">THE PROBLEM</p><h2>Finding papers is not the same as understanding evidence.</h2></div><div className="section-copy"><p>Scientific findings can support one another, conflict, carry different confidence levels, or expose questions no study has resolved. HelixMind is designed around that reality.</p><p>It keeps the literature as the source of truth while giving researchers a structured way to move from a question to a defensible scientific synthesis.</p></div></section>
    <section className="workflow-section"><div className="section-heading"><p className="eyebrow">THE RESEARCH LOOP</p><h2>From question to structured intelligence.</h2></div><div className="workflow">{workflow.map((item, i) => <div className="workflow-item" key={item}><span>{String(i + 1).padStart(2, '0')}</span><b>{item}</b>{i < workflow.length - 1 && <i>→</i>}</div>)}</div></section>
    <section id="stack" className="section stack-section"><div className="section-heading"><p className="eyebrow">THE HELIXMIND STACK</p><h2>Reasoning with structure, uncertainty and provenance.</h2></div><div className="stack-grid"><div><strong>Ω</strong><h3>OmegaClaw</h3><p>Orchestrates the research workflow: planning, retrieval, extraction and synthesis.</p></div><div><strong>∴</strong><h3>MeTTa / PeTTa</h3><p>Represents scientific entities and relationships in a form the reasoning runtime can consume.</p></div><div><strong>◌</strong><h3>PLN / NAL</h3><p>Reasons over relationships and evidence while keeping uncertainty explicit.</p></div><div><strong>✦</strong><h3>LLM assistance</h3><p>Helps plan, interpret and synthesize; it does not replace source evidence or formal review.</p></div></div></section>
    <section id="crispr" className="domain-section"><div className="domain-mark">CRISPR<br /><span>01</span></div><div><p className="eyebrow">INITIAL SCIENTIFIC DOMAIN</p><h2>Biotechnology, genomics and the questions that matter.</h2><p>Start with gene editing, genetic disease, delivery mechanisms, off-target effects, gene regulation and emerging clinical evidence. Extend the same evidence architecture to new domains over time.</p><p className="disclaimer">HelixMind is a research intelligence tool—not a diagnostic system, treatment recommendation engine, clinician, or substitute for peer review.</p></div></section>
    <section className="section capabilities-section"><div className="section-heading"><p className="eyebrow">A RESEARCH WORKSTATION</p><h2>Make the evidence chain legible.</h2></div><div className="capabilities">{capabilities.map(([number, title, text]) => <div key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section className="cta-section"><p className="eyebrow">BEGIN WITH A QUESTION</p><h2>Turn scientific literature into structured intelligence.</h2><div><Link href="/login" className="button">Start an investigation <span>↗</span></Link><Link href="/login" className="button button-ghost">Sign in</Link></div></section>
    <footer><Brand /><span>Source evidence / AI interpretation / system inference — always distinguished.</span><span>© 2026 HelixMind</span></footer>
  </main>;
}
