"""create helixmind scientific schema

Revision ID: 9cc407dfbcb0
Revises:
Create Date: 2026-08-20 23:41:44.960070
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '9cc407dfbcb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_type_canonical_name', 'entities', ['entity_type', 'canonical_name'], unique=True)
    op.create_table('investigations',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('research_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synthesis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigations_status_created_at', 'investigations', ['status', 'created_at'], unique=False)
    op.create_table('papers',
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index('ix_papers_source_external_id', 'papers', ['source', 'external_id'], unique=True)
    op.create_table('agent_runs',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.String(length=128), nullable=False),
    sa.Column('skill', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_investigation_status', 'agent_runs', ['investigation_id', 'status'], unique=False)
    op.create_table('hypotheses',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('strength', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hypotheses_investigation_status', 'hypotheses', ['investigation_id', 'status'], unique=False)
    op.create_table('investigation_events',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigation_events_investigation_timestamp', 'investigation_events', ['investigation_id', 'timestamp'], unique=False)
    op.create_table('knowledge_gaps',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_gaps_investigation_id'), 'knowledge_gaps', ['investigation_id'], unique=False)
    op.create_table('relationships',
    sa.Column('subject_entity_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.String(length=64), nullable=False),
    sa.Column('object_entity_id', sa.UUID(), nullable=False),
    sa.Column('strength', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relationships_predicate', 'relationships', ['predicate'], unique=False)
    op.create_table('evidence',
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('relationship_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('strength', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_relationship_id', 'evidence', ['relationship_id'], unique=False)
    op.create_table('inferences',
    sa.Column('hypothesis_id', sa.UUID(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('strength', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inferences_hypothesis_id'), 'inferences', ['hypothesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inferences_hypothesis_id'), table_name='inferences')
    op.drop_table('inferences')
    op.drop_index('ix_evidence_relationship_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_relationships_predicate', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_knowledge_gaps_investigation_id'), table_name='knowledge_gaps')
    op.drop_table('knowledge_gaps')
    op.drop_index('ix_investigation_events_investigation_timestamp', table_name='investigation_events')
    op.drop_table('investigation_events')
    op.drop_index('ix_hypotheses_investigation_status', table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index('ix_agent_runs_investigation_status', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_papers_source_external_id', table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_index('ix_investigations_status_created_at', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('ix_entities_type_canonical_name', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
